services:
  peril_rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672" # Amqp port
      - "15672:15672" # Management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
      RABBITMQ_CONF_FILE: /etc/rabbitmq/rabbitmq.conf
